version: '3'

services:
  httpd:
    build: .
    image: attendtrack:latest
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-password
      MYSQL_DATABASE: attendtrack
      MYSQL_USER: attendtrack
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
