version: '3'

services:
  httpd:
    build: .
    image: attendtrack:latest
    ports:
      - "4000:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.1
    env_file:
      - ./db_secrets.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
